-- Run this in Supabase SQL Editor to add all new skills
-- Uses ON CONFLICT to skip existing ones

INSERT INTO skills (name, slug) VALUES
  -- Dev / Engineering
  ('C++', 'cpp'),
  ('C#', 'csharp'),
  ('Swift', 'swift'),
  ('Kotlin', 'kotlin'),
  ('PHP', 'php'),
  ('Ruby', 'ruby'),
  ('Scala', 'scala'),
  ('Elixir', 'elixir'),
  ('Vue.js', 'vuejs'),
  ('Angular', 'angular'),
  ('Svelte', 'svelte'),
  ('Django', 'django'),
  ('Spring Boot', 'spring-boot'),
  ('Laravel', 'laravel'),
  ('Express.js', 'expressjs'),
  ('REST APIs', 'rest-apis'),
  ('MySQL', 'mysql'),
  ('Redis', 'redis'),
  ('Elasticsearch', 'elasticsearch'),
  ('Google Cloud', 'gcp'),
  ('Azure', 'azure'),
  ('Kubernetes', 'kubernetes'),
  ('Terraform', 'terraform'),
  ('CI/CD', 'ci-cd'),
  ('Linux', 'linux'),
  ('Git', 'git'),
  ('Microservices', 'microservices'),
  ('System Design', 'system-design'),
  ('Solidity', 'solidity'),
  ('Web3', 'web3'),
  ('Embedded Systems', 'embedded-systems'),
  ('IoT', 'iot'),

  -- AI / ML / Data
  ('Deep Learning', 'deep-learning'),
  ('Natural Language Processing', 'nlp'),
  ('Computer Vision', 'computer-vision'),
  ('PyTorch', 'pytorch'),
  ('TensorFlow', 'tensorflow'),
  ('LLMs', 'llms'),
  ('Prompt Engineering', 'prompt-engineering'),
  ('MLOps', 'mlops'),
  ('Data Engineering', 'data-engineering'),
  ('Data Analytics', 'data-analytics'),
  ('Power BI', 'power-bi'),
  ('Tableau', 'tableau'),
  ('SQL', 'sql'),
  ('R', 'r-lang'),
  ('Statistics', 'statistics'),
  ('A/B Testing', 'ab-testing'),

  -- Design / Creative
  ('UX Design', 'ux-design'),
  ('UX Research', 'ux-research'),
  ('Adobe XD', 'adobe-xd'),
  ('Photoshop', 'photoshop'),
  ('Illustrator', 'illustrator'),
  ('After Effects', 'after-effects'),
  ('Premiere Pro', 'premiere-pro'),
  ('3D Design', '3d-design'),
  ('Graphic Design', 'graphic-design'),
  ('Brand Design', 'brand-design'),
  ('Animation', 'animation'),
  ('Design Systems', 'design-systems'),

  -- Product / Management
  ('Product Strategy', 'product-strategy'),
  ('Agile', 'agile'),
  ('Scrum', 'scrum'),
  ('JIRA', 'jira'),
  ('Project Management', 'project-management'),
  ('Program Management', 'program-management'),
  ('Business Analysis', 'business-analysis'),
  ('Technical Writing', 'technical-writing'),
  ('Roadmapping', 'roadmapping'),

  -- Marketing / Growth
  ('Digital Marketing', 'digital-marketing'),
  ('Content Marketing', 'content-marketing'),
  ('Copywriting', 'copywriting'),
  ('SEM', 'sem'),
  ('Google Ads', 'google-ads'),
  ('Meta Ads', 'meta-ads'),
  ('Social Media Marketing', 'social-media-marketing'),
  ('Email Marketing', 'email-marketing'),
  ('Growth Hacking', 'growth-hacking'),
  ('Performance Marketing', 'performance-marketing'),
  ('Influencer Marketing', 'influencer-marketing'),
  ('Brand Management', 'brand-management'),
  ('PR & Communications', 'pr-communications'),
  ('Market Research', 'market-research'),
  ('CRM', 'crm'),
  ('HubSpot', 'hubspot'),
  ('Salesforce', 'salesforce'),

  -- Sales / Business
  ('Sales', 'sales'),
  ('Business Development', 'business-development'),
  ('Account Management', 'account-management'),
  ('Enterprise Sales', 'enterprise-sales'),
  ('Inside Sales', 'inside-sales'),
  ('Negotiation', 'negotiation'),
  ('Lead Generation', 'lead-generation'),
  ('Partnership Management', 'partnership-management'),
  ('Customer Success', 'customer-success'),
  ('Client Relations', 'client-relations'),

  -- Finance / Accounting
  ('Financial Analysis', 'financial-analysis'),
  ('Financial Modeling', 'financial-modeling'),
  ('Accounting', 'accounting'),
  ('Tally', 'tally'),
  ('SAP', 'sap'),
  ('Taxation', 'taxation'),
  ('GST', 'gst'),
  ('Audit', 'audit'),
  ('Investment Banking', 'investment-banking'),
  ('Venture Capital', 'venture-capital'),
  ('Private Equity', 'private-equity'),
  ('Risk Management', 'risk-management'),
  ('Compliance', 'compliance'),
  ('Corporate Finance', 'corporate-finance'),
  ('FP&A', 'fp-and-a'),
  ('Excel', 'excel'),
  ('Bookkeeping', 'bookkeeping'),
  ('Payroll', 'payroll'),

  -- HR / People
  ('Human Resources', 'human-resources'),
  ('Talent Acquisition', 'talent-acquisition'),
  ('Recruiting', 'recruiting'),
  ('Employer Branding', 'employer-branding'),
  ('People Operations', 'people-operations'),
  ('Learning & Development', 'learning-development'),
  ('Compensation & Benefits', 'compensation-benefits'),
  ('HRIS', 'hris'),
  ('Organizational Development', 'org-development'),

  -- Legal
  ('Corporate Law', 'corporate-law'),
  ('Contract Drafting', 'contract-drafting'),
  ('IP Law', 'ip-law'),
  ('Labour Law', 'labour-law'),
  ('Legal Compliance', 'legal-compliance'),
  ('GDPR', 'gdpr'),
  ('Data Privacy', 'data-privacy'),

  -- Medical / Healthcare
  ('Clinical Research', 'clinical-research'),
  ('Medical Writing', 'medical-writing'),
  ('Pharmacology', 'pharmacology'),
  ('Pharmacy', 'pharmacy'),
  ('Nursing', 'nursing'),
  ('Public Health', 'public-health'),
  ('Epidemiology', 'epidemiology'),
  ('Health Informatics', 'health-informatics'),
  ('Biostatistics', 'biostatistics'),
  ('Medical Devices', 'medical-devices'),
  ('Regulatory Affairs', 'regulatory-affairs'),
  ('Biotechnology', 'biotechnology'),
  ('Genomics', 'genomics'),
  ('Telemedicine', 'telemedicine'),
  ('Healthcare Management', 'healthcare-management'),
  ('Physiotherapy', 'physiotherapy'),
  ('Radiology', 'radiology'),
  ('Pathology', 'pathology'),

  -- Operations / Supply Chain
  ('Operations Management', 'operations-management'),
  ('Supply Chain', 'supply-chain'),
  ('Logistics', 'logistics'),
  ('Procurement', 'procurement'),
  ('Warehouse Management', 'warehouse-management'),
  ('Inventory Management', 'inventory-management'),
  ('Quality Assurance', 'quality-assurance'),
  ('Six Sigma', 'six-sigma'),
  ('Lean Management', 'lean-management'),

  -- Cybersecurity
  ('Cybersecurity', 'cybersecurity'),
  ('Penetration Testing', 'penetration-testing'),
  ('SOC', 'soc'),
  ('SIEM', 'siem'),
  ('Network Security', 'network-security'),
  ('Cloud Security', 'cloud-security'),
  ('Ethical Hacking', 'ethical-hacking'),

  -- Education / Training
  ('Teaching', 'teaching'),
  ('Curriculum Design', 'curriculum-design'),
  ('E-Learning', 'e-learning'),
  ('Instructional Design', 'instructional-design'),
  ('EdTech', 'edtech'),
  ('Tutoring', 'tutoring'),
  ('Corporate Training', 'corporate-training'),

  -- Other
  ('Entrepreneurship', 'entrepreneurship'),
  ('Public Speaking', 'public-speaking'),
  ('Leadership', 'leadership'),
  ('Strategy Consulting', 'strategy-consulting'),
  ('Management Consulting', 'management-consulting'),
  ('Customer Support', 'customer-support'),
  ('Technical Support', 'technical-support'),
  ('Community Management', 'community-management'),
  ('Event Management', 'event-management'),
  ('Real Estate', 'real-estate'),
  ('Architecture', 'architecture'),
  ('Civil Engineering', 'civil-engineering'),
  ('Mechanical Engineering', 'mechanical-engineering'),
  ('Electrical Engineering', 'electrical-engineering'),
  ('Automobile Engineering', 'automobile-engineering')
ON CONFLICT (slug) DO NOTHING;
